# Site settings
author: Ashley Shaw
title: Working Through Code
header-img: img/home-bg.png
email: aprier091012@gmail.com
copyright_name: Ashley Shaw
description: > # this means to ignore newlines until "baseurl:"
  My adventures in coding!!!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AShaw2019

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
